version: '3'
services:
    php-apache:
        build:
            context: ./php-apache
        ports:
            - 80:80
        volumes:
            - ../project:/var/www/html
        links:
            - 'mariadb'
    
    mariadb:
        image: mariadb:10.1
        volumes:
            - mariadb:/var/lib/mysql
        environment:
            TZ: "Europe/Rome"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_DATABASE: 'default'
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mariadb:mysql
        ports:
            - 8080:80
        environment:
            MYSQL_USERNAME: 'user'
            MYSQL_ROOT_PASSWORD: 'root'
            PMA_HOST: mariadb
volumes:
    mariadb: